fix: 用户收到的备份内容缺失
MamaShip/Observer pull request #65
Opened 2020-06-07 10:41 UTC by ChenliangLi205

并且加上了logger

close #63

2020-06-07 12:13 UTC, MamaShip requested changes
提的检视意见看一下，我们先改好了再合入。

2020-06-07 12:13 UTC, MamaShip commented on article_checker/article_checker.py
> +logger = logging.getLogger("article_checker")
这样子记的话，会记到全局的日志里混在一起，不方便追。

抄一下 main.py 里的相关代码，指定一个专门的 log 文件来保存

2020-06-07 12:13 UTC, MamaShip commented on database/db_operator.py
> +    "  `title` varchar(2048) NULL,"
这个 NULL 应该不用吧，直接把 NOT NULL 去掉就行的

2020-06-07 12:13 UTC, MamaShip commented on database/db_operator.py
> +    "  DEFAULT CHARACTER SET = utf8;")
不确定这样改是否有效，这个还要到时候在服务器上再验一下

2020-06-07 12:13 UTC, MamaShip commented on database/db_operator.py
>  TABLES['archive'] = (
表结构这里也要改一下，让 archive 表的结构跟 article 表完全保持一致。

2020-06-07 12:15 UTC, MamaShip commented on database/db_operator.py
>  TABLES['archive'] = (
不对，它也不是完全一致的，它多了个 `end_date`

2020-06-07 13:15 UTC, ChenliangLi205 commented
改好了

2020-06-07 13:22 UTC, MamaShip approved these changes

2020-06-07 15:11 UTC, merged

2020-06-09 03:32 UTC, MamaShip commented on observer.py
> +                    title = optionals["title"]
存入数据库前未对输入进行校验。这里可能超长，有缓冲区溢出的风险。注意一下。 @ChenliangLi205 

实际 MySQL 那边比较健壮，会对输入字符串做截断，所以不会出问题。但是我猜你并没有考虑到这一层。